    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build -- --configuration production --base-href=/SignIt/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/browser
